### PR TITLE
Update from study-template

### PR DESCRIPTION
**Pull request by bernardlee**
Refresh for cohort 016.

### CODE REVIEW

**Comment by BenGitsCode** [comment]
@bernardlee Did you make a solution branch for this?

**Comment by bernardlee** [comment]
Yes.  It just hasn't been pushed up.

**Comment by BenGitsCode** [comment]
OK, go ahead and push that up now. I'll merge this now.

**Review by BenGitsCode — APPROVED** [review]
Good to merge

**Pull request merged**
